# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /i/browsers/vc71compat/mozilla-vc71-dev/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/local/bin:/c/mozilla-build/Version1.5.1/wget:/c/mozilla-build/Version1.5.1/7zip:/c/mozilla-build/Version1.5.1/blat261/full:/c/mozilla-build/Version1.5.1/python:/c/mozilla-build/Version1.5.1/svn-win32-1.6.3/bin:/c/mozilla-build/Version1.5.1/upx203w:/c/mozilla-build/Version1.5.1/emacs-22.3/bin:/c/mozilla-build/Version1.5.1/info-zip:/c/mozilla-build/Version1.5.1/nsis-2.22:/c/mozilla-build/Version1.5.1/nsis-2.33u:/c/mozilla-build/Version1.5.1/nsis-2.46u:/c/mozilla-build/Version1.5.1/wix-351728:/c/mozilla-build/Version1.5.1/hg:/c/mozilla-build/Version1.5.1/python/Scripts:/c/mozilla-build/Version1.5.1/kdiff3:/c/mozilla-build/Version1.5.1/yasm:.:/usr/local/bin:/mingw/bin:/bin:/c/Program Files/Microsoft SDKs/Windows/v6.0A/bin:/c/Program Files/Microsoft Platform SDK for Windows Server 2003 R2/bin:/c/Program Files/Microsoft Visual Studio .NET 2003/Common7/IDE:/c/Program Files/Microsoft Visual Studio .NET 2003/VC7/BIN:/c/Program Files/Microsoft Visual Studio .NET 2003/Common7/Tools:/c/Program Files/Microsoft Visual Studio .NET 2003/Common7/Tools/bin/prerelease:/c/Program Files/Microsoft Visual Studio .NET 2003/Common7/Tools/bin:/c/Program Files/Microsoft Visual Studio .NET 2003/SDK/v1.1/bin:/c/WINDOWS/Microsoft.NET/Framework/v1.1.4322:/c/WINDOWS/System32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/mozilla-build/Version1.5.1/moztools/bin:.:/c/mozilla-build/Version1.5.1/vim/vim72
MOZ_MAKE_FLAGS=-j1
MOZ_OBJDIR=/i/Browsers/VC71Compat/objdir/obj-fxvc71-release
# --target=i686-pc-mingw32 is used by configure (not client.mk)
# --enable-application=browser is used by configure (not client.mk)
# --enable-optimize is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --disable-debug-symbols is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --without-system-jpg is used by configure (not client.mk)
# --without-system-zlib is used by configure (not client.mk)
# --enable-crypto is used by configure (not client.mk)
# --enable-svg is used by configure (not client.mk)
# --enable-canvas is used by configure (not client.mk)
# --disable-activex is used by configure (not client.mk)
# --disable-activex-scripting is used by configure (not client.mk)
# --disable-updater is used by configure (not client.mk)
# --disable-accessibility is used by configure (not client.mk)
# --enable-default-toolkit=cairo-windows is used by configure (not client.mk)
# --enable-libxul is used by configure (not client.mk)
# --disable-crashreporter is used by configure (not client.mk)
# --disable-vista-sdk-requirements is used by configure (not client.mk)
# --disable-webgl is used by configure (not client.mk)
# --disable-angle is used by configure (not client.mk)
# --disable-gamepad is used by configure (not client.mk)
# --disable-methodjit is used by configure (not client.mk)
# --disable-tracejit is used by configure (not client.mk)
# --disable-jit is used by configure (not client.mk)
# --disable-ipc is used by configure (not client.mk)
# --disable-webm is used by configure (not client.mk)
# --disable-sps is used by configure (not client.mk)
# --disable-skia is used by configure (not client.mk)
# --disable-maintenance-service is used by configure (not client.mk)
# --disable-updater is used by configure (not client.mk)
# --disable-cubeb is used by configure (not client.mk)
# --disable-websms-backend is used by configure (not client.mk)
# --with-windows-version=502 is used by configure (not client.mk)
